#!/usr/bin/env python3
"""Generate a compact C++ fixture from SingleStepTests/z80 v1 JSON files."""

import argparse
import json
from pathlib import Path


REGISTER_ORDER = (
    "a", "f", "b", "c", "d", "e", "h", "l", "i", "r",
    "ix", "iy", "sp", "pc", "af_", "bc_", "de_", "hl_",
    "im", "iff1", "iff2", "ei", "q", "wz",
)


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def registers(state: dict) -> str:
    return "{" + ", ".join(str(int(state.get(key, 0))) for key in REGISTER_ORDER) + "}"


def memory(values: list) -> str:
    return "{" + ", ".join("{%d, %d}" % (int(address), int(value)) for address, value in values) + "}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="SingleStepTests/z80 v1 directory")
    parser.add_argument("output", type=Path)
    parser.add_argument("--revision", required=True)
    args = parser.parse_args()

    cases = []
    skipped_io = 0
    for path in sorted(args.source.glob("*.json")):
        tests = json.loads(path.read_text(encoding="utf-8"))
        selected = next((test for test in tests if not test.get("ports")), None)
        if selected is None:
            skipped_io += 1
            continue
        cases.append(selected)

    lines = [
        "// Generated by tools/import_z80_conformance.py.",
        "// Source: https://github.com/SingleStepTests/z80",
        f"// Revision: {args.revision}",
        f"// Cases: {len(cases)}; opcode sequences skipped because every vector used I/O: {skipped_io}",
        "const std::vector<ExternalCase> kExternalCases{",
    ]
    for test in cases:
        lines.append(
            "    {%s, %s, %s, %d, %s, %s},"
            % (
                cpp_string(test["name"]),
                registers(test["initial"]),
                registers(test["final"]),
                len(test["cycles"]),
                memory(test["initial"].get("ram", [])),
                memory(test["final"].get("ram", [])),
            )
        )
    lines.append("};")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(cases)} cases; skipped {skipped_io} I/O-only sequences")


if __name__ == "__main__":
    main()
